test:
	g++ test.cpp src.cpp -larmadillo -g -O0 -o test.exe
	./test.exe
debug:
	g++ main.cpp src.cpp -larmadillo -g -O0 -o main.exe
scrub:
	rm a.out PT*txt *.exe *.png *.pdf
clean:
	rm PT*.txt *.png *.pdf
